// Sample data for Teacher Differentiation Dashboard (JavaScript)

// Classroom objects
export const classrooms = [
  { id: '1', name: 'الصف الرابع أ', grade: '4' },
  { id: '2', name: 'الصف الرابع ب', grade: '4' },
  { id: '3', name: 'الصف الخامس أ', grade: '5' },
];

// Interventions library
export const interventions = [
  {
    id: 'int1',
    title: 'قراءة بصوت عالٍ',
    titleEn: 'Read Aloud',
    description: 'قراءة النص بصوت عالٍ للطالب مع متابعة بصرية',
    difficulty: 'easy',
    tags: ['ضعف قراءة', 'بصري', 'سمعي'],
  },
  {
    id: 'int2',
    title: 'خرائط ذهنية',
    titleEn: 'Mind Maps',
    description: 'استخدام الخرائط الذهنية لتنظيم الأفكار',
    difficulty: 'medium',
    tags: ['بصري', 'متميز'],
  },
  {
    id: 'int3',
    title: 'كتابة على الحاسوب',
    titleEn: 'Digital Writing',
    description: 'السماح بالكتابة على الحاسوب بدلاً من الكتابة اليدوية',
    difficulty: 'easy',
    tags: ['بطيء كتابة', 'عسر كتابة'],
  },
  {
    id: 'int4',
    title: 'فترات راحة قصيرة',
    titleEn: 'Short Breaks',
    description: 'فترات راحة منتظمة كل 15 دقيقة',
    difficulty: 'easy',
    tags: ['ADHD', 'حركي'],
  },
  {
    id: 'int5',
    title: 'أنشطة حركية',
    titleEn: 'Kinesthetic Activities',
    description: 'استخدام الأنشطة الحركية في الشرح',
    difficulty: 'medium',
    tags: ['حركي', 'ADHD'],
  },
  {
    id: 'int6',
    title: 'تسجيلات صوتية',
    titleEn: 'Audio Recordings',
    description: 'توفير تسجيلات صوتية للدروس',
    difficulty: 'easy',
    tags: ['سمعي', 'ضعف قراءة'],
  },
  {
    id: 'int7',
    title: 'تحديات إضافية',
    titleEn: 'Extra Challenges',
    description: 'مهام إضافية متقدمة للطلاب المتميزين',
    difficulty: 'hard',
    tags: ['متميز'],
  },
  {
    id: 'int8',
    title: 'شريك قراءة',
    titleEn: 'Reading Partner',
    description: 'إقران الطالب مع زميل قوي في القراءة',
    difficulty: 'easy',
    tags: ['ضعف قراءة'],
  },
  {
    id: 'int9',
    title: 'وقت إضافي',
    titleEn: 'Extended Time',
    description: 'منح وقت إضافي لإتمام المهام',
    difficulty: 'easy',
    tags: ['بطيء كتابة', 'عسر كتابة'],
  },
  {
    id: 'int10',
    title: 'مواد بصرية',
    titleEn: 'Visual Materials',
    description: 'استخدام الصور والرسوم التوضيحية',
    difficulty: 'medium',
    tags: ['بصري', 'ضعف قراءة'],
  },
];

// Students
export const students = [
  {
    id: 's1',
    name: 'أحمد محمد',
    nameEn: 'Ahmed Mohammed',
    dob: '2014-03-15',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed',
    tags: ['ضعف قراءة', 'سمعي'],
    learning_style: 'auditory',
    strengths: ['رياضيات', 'استماع'],
    difficulties: ['القراءة', 'التهجئة'],
    interventionLogs: [
      {
        id: 'log1',
        interventionId: 'int1',
        interventionTitle: 'قراءة بصوت عالٍ',
        date: '2025-11-10',
        outcome: 'success',
        notes: 'تحسن ملحوظ في الفهم',
      },
      {
        id: 'log2',
        interventionId: 'int6',
        interventionTitle: 'تسجيلات صوتية',
        date: '2025-11-08',
        outcome: 'success',
        notes: 'استجابة ممتازة',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-10',
    },
  },
  {
    id: 's2',
    name: 'فاطمة علي',
    nameEn: 'Fatima Ali',
    dob: '2014-05-22',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima',
    tags: ['متميز', 'بصري'],
    learning_style: 'visual',
    strengths: ['القراءة', 'الكتابة', 'الإبداع'],
    difficulties: [],
    interventionLogs: [
      {
        id: 'log3',
        interventionId: 'int7',
        interventionTitle: 'تحديات إضافية',
        date: '2025-11-12',
        outcome: 'success',
        notes: 'أنهت المهام المتقدمة بتميز',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-12',
    },
  },
  {
    id: 's3',
    name: 'محمود خالد',
    nameEn: 'Mahmoud Khaled',
    dob: '2014-01-10',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mahmoud',
    tags: ['ADHD', 'حركي'],
    learning_style: 'kinesthetic',
    strengths: ['الأنشطة العملية', 'الرياضة'],
    difficulties: ['التركيز', 'الجلوس لفترات طويلة'],
    interventionLogs: [
      {
        id: 'log4',
        interventionId: 'int4',
        interventionTitle: 'فترات راحة قصيرة',
        date: '2025-11-11',
        outcome: 'partial',
        notes: 'تحسن طفيف',
      },
      {
        id: 'log5',
        interventionId: 'int5',
        interventionTitle: 'أنشطة حركية',
        date: '2025-11-09',
        outcome: 'success',
        notes: 'تفاعل ممتاز',
      },
    ],
    lastIntervention: {
      outcome: 'partial',
      date: '2025-11-11',
    },
  },
  {
    id: 's4',
    name: 'مريم حسن',
    nameEn: 'Mariam Hassan',
    dob: '2014-07-18',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mariam',
    tags: ['بطيء كتابة', 'عسر كتابة'],
    learning_style: 'visual',
    strengths: ['الفهم الشفوي', 'الإبداع'],
    difficulties: ['الكتابة اليدوية', 'سرعة الإنجاز'],
    interventionLogs: [
      {
        id: 'log6',
        interventionId: 'int3',
        interventionTitle: 'كتابة على الحاسوب',
        date: '2025-11-10',
        outcome: 'success',
        notes: 'تحسن كبير في الإنتاجية',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-10',
    },
  },
  {
    id: 's5',
    name: 'يوسف عمر',
    nameEn: 'Youssef Omar',
    dob: '2014-09-05',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=youssef',
    tags: ['بصري', 'ضعف قراءة'],
    learning_style: 'visual',
    strengths: ['الرسم', 'التفكير المكاني'],
    difficulties: ['القراءة'],
    interventionLogs: [
      {
        id: 'log7',
        interventionId: 'int10',
        interventionTitle: 'مواد بصرية',
        date: '2025-11-13',
        outcome: 'success',
        notes: 'استيعاب أفضل',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-13',
    },
  },
  {
    id: 's6',
    name: 'نور إبراهيم',
    nameEn: 'Nour Ibrahim',
    dob: '2014-04-12',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nour',
    tags: ['سمعي'],
    learning_style: 'auditory',
    strengths: ['الاستماع', 'المناقشة'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's7',
    name: 'سارة أحمد',
    nameEn: 'Sara Ahmed',
    dob: '2014-06-20',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara',
    tags: ['متميز', 'بصري'],
    learning_style: 'visual',
    strengths: ['العلوم', 'التحليل'],
    difficulties: [],
    interventionLogs: [
      {
        id: 'log8',
        interventionId: 'int2',
        interventionTitle: 'خرائط ذهنية',
        date: '2025-11-12',
        outcome: 'success',
        notes: 'نتائج ممتازة',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-12',
    },
  },
  {
    id: 's8',
    name: 'خالد سعيد',
    nameEn: 'Khaled Saeed',
    dob: '2014-02-28',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=khaled',
    tags: ['ضعف قراءة'],
    learning_style: 'kinesthetic',
    strengths: ['الرياضة', 'العمل اليدوي'],
    difficulties: ['القراءة', 'الكتابة'],
    interventionLogs: [
      {
        id: 'log9',
        interventionId: 'int8',
        interventionTitle: 'شريك قراءة',
        date: '2025-11-11',
        outcome: 'partial',
        notes: 'يحتاج مزيد من الدعم',
      },
    ],
    lastIntervention: {
      outcome: 'partial',
      date: '2025-11-11',
    },
  },
  {
    id: 's9',
    name: 'ليلى حسين',
    nameEn: 'Layla Hussein',
    dob: '2014-08-14',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=layla',
    tags: ['بصري', 'متميز'],
    learning_style: 'visual',
    strengths: ['الفنون', 'اللغة العربية'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's10',
    name: 'عبدالله ناصر',
    nameEn: 'Abdullah Nasser',
    dob: '2014-11-03',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=abdullah',
    tags: ['ADHD', 'حركي'],
    learning_style: 'kinesthetic',
    strengths: ['الطاقة العالية', 'القيادة'],
    difficulties: ['التركيز', 'الانتباه'],
    interventionLogs: [
      {
        id: 'log10',
        interventionId: 'int4',
        interventionTitle: 'فترات راحة قصيرة',
        date: '2025-11-13',
        outcome: 'success',
        notes: 'تحسن في التركيز',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-13',
    },
  },
  {
    id: 's11',
    name: 'ريم فهد',
    nameEn: 'Reem Fahad',
    dob: '2014-12-01',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reem',
    tags: ['بطيء كتابة'],
    learning_style: 'auditory',
    strengths: ['الاستماع'],
    difficulties: ['الكتابة'],
    interventionLogs: [
      {
        id: 'log11',
        interventionId: 'int9',
        interventionTitle: 'وقت إضافي',
        date: '2025-11-12',
        outcome: 'success',
        notes: 'أكملت المهام بنجاح',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-12',
    },
  },
  {
    id: 's12',
    name: 'طارق زيد',
    nameEn: 'Tarek Zaid',
    dob: '2014-10-17',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tarek',
    tags: ['سمعي', 'ضعف قراءة'],
    learning_style: 'auditory',
    strengths: ['الموسيقى', 'الإيقاع'],
    difficulties: ['القراءة'],
    interventionLogs: [],
  },
  {
    id: 's13',
    name: 'دانة سالم',
    nameEn: 'Dana Salem',
    dob: '2014-03-25',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dana',
    tags: ['بصري'],
    learning_style: 'visual',
    strengths: ['التنظيم', 'الدقة'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's14',
    name: 'عمر جمال',
    nameEn: 'Omar Jamal',
    dob: '2014-05-08',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omar',
    tags: ['حركي'],
    learning_style: 'kinesthetic',
    strengths: ['النشاط البدني'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's15',
    name: 'هند راشد',
    nameEn: 'Hend Rashed',
    dob: '2014-07-30',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hend',
    tags: ['متميز', 'بصري'],
    learning_style: 'visual',
    strengths: ['الرياضيات', 'التفكير المنطقي'],
    difficulties: [],
    interventionLogs: [
      {
        id: 'log12',
        interventionId: 'int7',
        interventionTitle: 'تحديات إضافية',
        date: '2025-11-10',
        outcome: 'success',
        notes: 'أداء متميز',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-10',
    },
  },
  {
    id: 's16',
    name: 'حمزة وليد',
    nameEn: 'Hamza Waleed',
    dob: '2014-01-19',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hamza',
    tags: ['ضعف قراءة', 'بطيء كتابة'],
    learning_style: 'kinesthetic',
    strengths: ['العمل الجماعي'],
    difficulties: ['القراءة', 'الكتابة'],
    interventionLogs: [
      {
        id: 'log13',
        interventionId: 'int1',
        interventionTitle: 'قراءة بصوت عالٍ',
        date: '2025-11-09',
        outcome: 'partial',
        notes: 'يحتاج متابعة',
      },
    ],
    lastIntervention: {
      outcome: 'partial',
      date: '2025-11-09',
    },
  },
  {
    id: 's17',
    name: 'جنى ماجد',
    nameEn: 'Jana Majed',
    dob: '2014-04-07',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jana',
    tags: ['سمعي'],
    learning_style: 'auditory',
    strengths: ['التواصل', 'العرض'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's18',
    name: 'زياد كريم',
    nameEn: 'Ziad Kareem',
    dob: '2014-09-22',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ziad',
    tags: ['بصري', 'متميز'],
    learning_style: 'visual',
    strengths: ['العلوم', 'التكنولوجيا'],
    difficulties: [],
    interventionLogs: [],
  },
  {
    id: 's19',
    name: 'شهد طلال',
    nameEn: 'Shahad Talal',
    dob: '2014-06-15',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shahad',
    tags: ['عسر كتابة'],
    learning_style: 'visual',
    strengths: ['الفهم', 'التفكير النقدي'],
    difficulties: ['الكتابة اليدوية'],
    interventionLogs: [
      {
        id: 'log14',
        interventionId: 'int3',
        interventionTitle: 'كتابة على الحاسوب',
        date: '2025-11-11',
        outcome: 'success',
        notes: 'أداء ممتاز',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-11',
    },
  },
  {
    id: 's20',
    name: 'راكان سامي',
    nameEn: 'Rakan Sami',
    dob: '2014-02-11',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rakan',
    tags: ['حركي', 'ADHD'],
    learning_style: 'kinesthetic',
    strengths: ['الإبداع', 'حل المشكلات'],
    difficulties: ['الجلوس الطويل', 'التركيز'],
    interventionLogs: [
      {
        id: 'log15',
        interventionId: 'int5',
        interventionTitle: 'أنشطة حركية',
        date: '2025-11-13',
        outcome: 'success',
        notes: 'تفاعل إيجابي',
      },
    ],
    lastIntervention: {
      outcome: 'success',
      date: '2025-11-13',
    },
  },
];

// Teacher
export const teacher = {
  id: 't1',
  name: 'المعلمة نورة السالم',
  email: 'noura.alsalem@school.edu',
};
